export const TABLE_ACTION_TYPE = {
  REQUEST_TABLE_DATA: "REQUEST_TABLE_DATA",
  SUCCESS_TABLE_DATA: "SUCCESS_TABLE_DATA",
  FAILURE_TABLE_DATA: "FAILURE_TABLE_DATA",
  SEND_CAPSULE_DATA_TO_STORE: "SEND_CAPSULE_DATA_TO_STORE",
  GET_INDIVIDUAL_RECORD: "GET_INDIVIDUAL_RECORD",
  GET_INDIVIDUAL_RECORD_REQUEST: "GET_INDIVIDUAL_RECORD_REQUEST",
  GET_INDIVIDUAL_RECORD_SUCCESS: "GET_INDIVIDUAL_RECORD_SUCCESS",
  GET_INDIVIDUAL_RECORD_FAILURE: "GET_INDIVIDUAL_RECORD_FAILURE",
};
